# Generated by Django 5.1.4 on 2025-01-16 03:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('document', models.FileField(blank=True, upload_to='files/', verbose_name='첨부 파일')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('attatchments', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=0, max_digits=5), default=list, size=None)),
            ],
        ),
    ]
