# Generated by Django 5.1.4 on 2025-01-16 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_alter_attachment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='attatchments',
            new_name='attachments',
        ),
    ]
