# Generated by Django 5.1.4 on 2025-01-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_rename_attatchments_league_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='type',
        ),
    ]
