# Generated by Django 5.1.4 on 2025-01-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_remove_attachment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='name',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='document',
            field=models.FileField(upload_to='files/', verbose_name='첨부 파일'),
        ),
    ]
