# Generated by Django 5.1.4 on 2025-01-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_alter_attachment_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='attachments',
        ),
        migrations.AddField(
            model_name='league',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='league.attachment'),
        ),
    ]
