# Generated by Django 5.1.4 on 2025-01-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_remove_league_attachments_league_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='document',
            field=models.FileField(upload_to='notices/files/', verbose_name='첨부 파일'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
