# Generated by Django 5.1.4 on 2025-01-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_attachment_name_alter_attachment_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='document',
            field=models.FileField(upload_to='leagues/files/', verbose_name='첨부 파일'),
        ),
    ]
