# Generated by Django 5.1.4 on 2025-01-20 05:41

import config.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_alter_attachment_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='document',
            field=models.FileField(storage=config.supabase_storage.SupabaseStorage(), upload_to='leauges/files/', verbose_name='첨부 파일'),
        ),
    ]
