# Generated by Django 5.1.4 on 2025-01-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_attachment_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='author',
        ),
    ]
