# Generated by Django 5.1.4 on 2025-01-26 10:58

import config.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_alter_league_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='document',
            field=models.FileField(storage=config.supabase_storage.SupabaseStorage(), upload_to='leauges/kor_files/', verbose_name='첨부 파일'),
        ),
    ]
