# Generated by Django 5.1.4 on 2025-01-26 11:35

import config.supabase_storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_alter_attachment_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment_ENG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(storage=config.supabase_storage.SupabaseStorage(), upload_to='eng/leauges/files/', verbose_name='첨부 파일')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attachment',
            name='document',
            field=models.FileField(storage=config.supabase_storage.SupabaseStorage(), upload_to='kor/leauges/files/', verbose_name='첨부 파일'),
        ),
        migrations.CreateModel(
            name='League_ENG',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('attachments', models.ManyToManyField(blank=True, to='league.attachment_eng')),
            ],
        ),
    ]
