# Generated by Django 5.1.4 on 2025-01-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_attachment_eng_alter_attachment_document_league_eng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='league_eng',
            name='attachments',
        ),
        migrations.AddField(
            model_name='league',
            name='attachments',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league_eng',
            name='attachments',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
