# Generated by Django 5.1.4 on 2025-01-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_remove_league_attachments_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Attachment_ENG',
        ),
        migrations.RemoveField(
            model_name='league',
            name='content',
        ),
        migrations.RemoveField(
            model_name='league',
            name='date',
        ),
        migrations.RemoveField(
            model_name='league',
            name='title',
        ),
        migrations.RemoveField(
            model_name='league_eng',
            name='content',
        ),
        migrations.RemoveField(
            model_name='league_eng',
            name='date',
        ),
        migrations.RemoveField(
            model_name='league_eng',
            name='title',
        ),
        migrations.AlterField(
            model_name='league',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='league_eng',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
