# Generated by Django 5.1.4 on 2025-01-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0019_delete_attachment_delete_attachment_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='league_eng',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
