# Generated by Django 5.1.4 on 2025-01-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='test',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
