# Generated by Django 5.1.4 on 2025-01-20 04:42

import config.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_bottom',
            field=models.ImageField(blank=True, storage=config.supabase_storage.SupabaseStorage(), upload_to='posters/bottom/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_top',
            field=models.ImageField(blank=True, storage=config.supabase_storage.SupabaseStorage(), upload_to='posters/top/'),
        ),
    ]
