# Generated by Django 5.1.4 on 2025-01-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_event_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='others',
        ),
        migrations.AddField(
            model_name='event',
            name='others',
            field=models.ManyToManyField(to='event.etc'),
        ),
    ]
