# Generated by Django 5.1.4 on 2025-01-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_image_bottom_alter_event_image_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='register',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
