# Generated by Django 5.1.4 on 2025-01-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='others',
        ),
        migrations.DeleteModel(
            name='ETC',
        ),
        migrations.AddField(
            model_name='event',
            name='others',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
