# Generated by Django 5.1.4 on 2025-01-26 10:58

import config.supabase_storage
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_event_others_delete_etc_event_others'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_ENG',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('map', models.CharField(max_length=255)),
                ('register', models.CharField(max_length=255)),
                ('others', models.JSONField(blank=True, default=list)),
                ('image_top', models.ImageField(blank=True, storage=config.supabase_storage.SupabaseStorage(), upload_to='posters/eng/top/')),
                ('image_bottom', models.ImageField(blank=True, storage=config.supabase_storage.SupabaseStorage(), upload_to='posters/eng/bottom/')),
                ('leagues', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='image_bottom',
            field=models.ImageField(blank=True, storage=config.supabase_storage.SupabaseStorage(), upload_to='posters/kor/bottom/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_top',
            field=models.ImageField(blank=True, storage=config.supabase_storage.SupabaseStorage(), upload_to='posters/kor/top/'),
        ),
    ]
