# Generated by Django 5.1.4 on 2025-01-26 11:35

import config.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_eng_alter_event_image_bottom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_bottom',
            field=models.ImageField(blank=True, storage=config.supabase_storage.SupabaseStorage(), upload_to='kor/posters/bottom/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_top',
            field=models.ImageField(blank=True, storage=config.supabase_storage.SupabaseStorage(), upload_to='kor/posters/top/'),
        ),
        migrations.AlterField(
            model_name='event_eng',
            name='image_bottom',
            field=models.ImageField(blank=True, storage=config.supabase_storage.SupabaseStorage(), upload_to='eng/posters/bottom/'),
        ),
        migrations.AlterField(
            model_name='event_eng',
            name='image_top',
            field=models.ImageField(blank=True, storage=config.supabase_storage.SupabaseStorage(), upload_to='eng/posters/top/'),
        ),
    ]
