# Generated by Django 5.1.4 on 2025-01-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_event_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster_bottom',
            field=models.ImageField(blank=True, upload_to='posters/bottom/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster_top',
            field=models.ImageField(blank=True, upload_to='posters/top/'),
        ),
    ]
