# Generated by Django 5.1.4 on 2025-02-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_event_image_bottom_alter_event_image_top_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='volunteer',
            field=models.CharField(default='test.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_eng',
            name='volunteer',
            field=models.CharField(default='test.com', max_length=255),
            preserve_default=False,
        ),
    ]
