# Generated by Django 5.1.4 on 2025-01-12 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_event_poster_bottom_alter_event_poster_top'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='poster_bottom',
            new_name='images_bottom',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='poster_top',
            new_name='images_top',
        ),
    ]
