# Generated by Django 5.1.4 on 2025-01-12 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_rename_poster_bottom_event_images_bottom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='others',
        ),
        migrations.AddField(
            model_name='event',
            name='others',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='event.etc'),
        ),
    ]
