# Generated by Django 5.1.4 on 2025-01-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_remove_event_others_event_others'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='place',
            new_name='map',
        ),
    ]
