# Generated by Django 5.1.4 on 2025-01-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_rename_place_event_map'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='images_top',
            new_name='image_top',
        ),
    ]
