# Generated by Django 5.1.4 on 2025-01-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_rename_images_top_event_image_top'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='images_bottom',
            new_name='image_bottom',
        ),
    ]
