# Generated by Django 5.1.4 on 2025-01-17 06:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='notices/files/', verbose_name='첨부 파일')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('attachments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
            ],
        ),
    ]
