# Generated by Django 5.1.4 on 2025-01-31 07:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachments', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Notice_ENG',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachments', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
