# Generated by Django 5.1.4 on 2025-01-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='attachments',
            field=models.TextField(),
        ),
    ]
