# Generated by Django 5.1.4 on 2025-01-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_notice_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice_eng',
            name='attachments',
        ),
        migrations.AlterField(
            model_name='notice',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
