# Generated by Django 5.1.4 on 2025-01-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_alter_attachment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='notice',
            name='attachments',
        ),
        migrations.AddField(
            model_name='notice',
            name='attachments',
            field=models.ManyToManyField(to='notice.attachment'),
        ),
    ]
