# Generated by Django 5.1.4 on 2025-01-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_remove_notice_eng_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_eng',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
