# Generated by Django 5.1.4 on 2025-01-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_alter_attachment_id_remove_notice_attachments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='notice.attachment'),
        ),
    ]
