# Generated by Django 5.1.4 on 2025-01-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0007_alter_attachment_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
